// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: grpc/transfer.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyCmd_Cmd int32

const (
	ProxyCmd_Connect  ProxyCmd_Cmd = 0
	ProxyCmd_Exchange ProxyCmd_Cmd = 1
)

// Enum value maps for ProxyCmd_Cmd.
var (
	ProxyCmd_Cmd_name = map[int32]string{
		0: "Connect",
		1: "Exchange",
	}
	ProxyCmd_Cmd_value = map[string]int32{
		"Connect":  0,
		"Exchange": 1,
	}
)

func (x ProxyCmd_Cmd) Enum() *ProxyCmd_Cmd {
	p := new(ProxyCmd_Cmd)
	*p = x
	return p
}

func (x ProxyCmd_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyCmd_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_transfer_proto_enumTypes[0].Descriptor()
}

func (ProxyCmd_Cmd) Type() protoreflect.EnumType {
	return &file_grpc_transfer_proto_enumTypes[0]
}

func (x ProxyCmd_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyCmd_Cmd.Descriptor instead.
func (ProxyCmd_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_grpc_transfer_proto_rawDescGZIP(), []int{0, 0}
}

type ProxyCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd      ProxyCmd_Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=transfer.ProxyCmd_Cmd" json:"cmd,omitempty"`
	ClientId int32        `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Data     []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ProxyCmd) Reset() {
	*x = ProxyCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_transfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyCmd) ProtoMessage() {}

func (x *ProxyCmd) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_transfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyCmd.ProtoReflect.Descriptor instead.
func (*ProxyCmd) Descriptor() ([]byte, []int) {
	return file_grpc_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyCmd) GetCmd() ProxyCmd_Cmd {
	if x != nil {
		return x.Cmd
	}
	return ProxyCmd_Connect
}

func (x *ProxyCmd) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ProxyCmd) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_transfer_proto protoreflect.FileDescriptor

var file_grpc_transfer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22,
	0x86, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6d, 0x64, 0x12, 0x28, 0x0a, 0x03,
	0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6d,
	0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x10, 0x01, 0x32, 0x44, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x43, 0x6d, 0x64, 0x1a, 0x12, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6d, 0x64, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x69, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_transfer_proto_rawDescOnce sync.Once
	file_grpc_transfer_proto_rawDescData = file_grpc_transfer_proto_rawDesc
)

func file_grpc_transfer_proto_rawDescGZIP() []byte {
	file_grpc_transfer_proto_rawDescOnce.Do(func() {
		file_grpc_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_transfer_proto_rawDescData)
	})
	return file_grpc_transfer_proto_rawDescData
}

var file_grpc_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_transfer_proto_goTypes = []interface{}{
	(ProxyCmd_Cmd)(0), // 0: transfer.ProxyCmd.Cmd
	(*ProxyCmd)(nil),  // 1: transfer.ProxyCmd
}
var file_grpc_transfer_proto_depIdxs = []int32{
	0, // 0: transfer.ProxyCmd.cmd:type_name -> transfer.ProxyCmd.Cmd
	1, // 1: transfer.Transfer.SendData:input_type -> transfer.ProxyCmd
	1, // 2: transfer.Transfer.SendData:output_type -> transfer.ProxyCmd
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_transfer_proto_init() }
func file_grpc_transfer_proto_init() {
	if File_grpc_transfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_transfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_transfer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_transfer_proto_goTypes,
		DependencyIndexes: file_grpc_transfer_proto_depIdxs,
		EnumInfos:         file_grpc_transfer_proto_enumTypes,
		MessageInfos:      file_grpc_transfer_proto_msgTypes,
	}.Build()
	File_grpc_transfer_proto = out.File
	file_grpc_transfer_proto_rawDesc = nil
	file_grpc_transfer_proto_goTypes = nil
	file_grpc_transfer_proto_depIdxs = nil
}
